---
# tasks file for common
- name: "Update Packages on All Servers"
  apt:
    update_cache: yes

- name: "Install utilities"
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - git
  - tree
  